# Default values for db-schema.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: flyway/flyway
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

db:
  host: postgresql
  port: 5432
  name: postgres
  adminUser: postgres
  secret:
    name: postgresql
    key: postgres-password

