# migration/migration-job.yml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  labels:
    jobgroup: migration
    {{- include "db-migrate.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args:
        - migrate
        env:
        - name: FLYWAY_URL
          value: "jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.name }}"
        - name: FLYWAY_USER
          value: {{ .Values.db.adminUser }}
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  {{ .Values.db.secret.name }}
              key: {{ .Values.db.secret.key }}
              optional: false
        - name: FLYWAY_PLACEHOLDER_REPLACEMENT
          value: "true"
        - name: FLYWAY_PLACEHOLDERS_USERNAME
          value: {{ .Values.placeholders.username | quote }}
        - name: FLYWAY_PLACEHOLDERS_PASSWORD
          value: {{ .Values.placeholders.password | quote }}
        volumeMounts:
        - mountPath: /flyway/sql
          name: sql
      volumes:
      - name: sql
        configMap:
          name: {{ .Release.Name }}-migrations
      restartPolicy: Never
