apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-migrations
  labels:
    {{- include "db-migrate.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "migrations/*").AsConfig | indent 2 }}
